A framework to add more inputs for the playwright testing
Teradata/jupyter-demos pull request #671
Opened 2024-07-15 19:39 UTC by sreeramnitin

CSAE 380 

Support for more inputs

2024-07-24 10:46 UTC, adamtwo requested changes

2024-07-24 16:20 UTC, sreeramnitin commented on .tests/README.md
> +Note: Can use the cell or prompt from selecting the input
ya, Prompt takes priority if matched

2024-07-24 16:22 UTC, sreeramnitin commented on .tests/skip_files.txt
Ya, That was because of the previous bug. The script was thinking it was continuing successfully. But it was stuck in the  Shift+Enter input loop.

2024-07-24 16:25 UTC, sreeramnitin commented on .tests/skip_files.txt
I have added additional checks to make sure if the notebook is able to progress .tests/tests/jupytertest.spec.ts - line 179

2024-07-24 17:50 UTC, adamtwo commented on .tests/README.md
> +Note: Can use the cell or prompt from selecting the input
OK, got it. Could you please explain it in the readme?

2024-07-25 14:21 UTC, adamtwo approved these changes

2024-07-25 15:45 UTC, merged